language: node_js
node_js:
  - iojs
after_script
  - ./node_modules/karma/bin/karma start
  - node node_modules/lcov-filter/index.js ./coverage/lcov.info config | ./node_modules/coveralls/bin/coveralls.js
